stages:
  - test
  - reporting
  - coverage
  - documentation
  - pages
  - deploy
  - release

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: '$CI_COMMIT_BRANCH =~ /^(main|releases\/)/'

default:
  image: python:3.10

cache:
  paths:
    - .cache/pip

.regular_job:
  rules:
    - if: $FIELDCOMPARE_RELEASE_VERSION
      when: never
    - when: on_success

.release_job:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $FIELDCOMPARE_RELEASE_VERSION =~ /^(\d+\.)?(\d+\.)?(\*|\d+)$/

.install_dependencies:
  extends: .regular_job
  before_script:
      - python --version
      - pip install --upgrade pip
      - pip install tox

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PY_VERSION: "3.10"

test:
  stage: test
  extends: .install_dependencies
  image: python:$PY_VERSION
  artifacts:
    reports:
      junit: test_report.xml
  script:
    # TODO: simplify again and turn 3.10.4 -> 3.10 (once the mypy error with numpy is fixed)
    - env=${PY_VERSION//./}
    - tox -e py${env:0:3}
  parallel:
    matrix:
      - PY_VERSION: ["3.8", "3.9", "3.10.4"]

file_mode_junit_report:
  stage: reporting
  extends: .install_dependencies
  image: python:3.10
  script:
    - python -m pip install -r requirements.txt
    - python -m pip install .
    - fieldcompare file test/data/test_mesh.vtu -r test/data/test_mesh.vtu --exclude-fields "function" --junit-xml file_mode_junit.xml
  artifacts:
    reports:
      junit: file_mode_junit.xml

dir_mode_junit_report:
  stage: reporting
  extends: .install_dependencies
  image: python:3.10
  script:
    - python -m pip install -r requirements.txt
    - python -m pip install .
    - fieldcompare dir test/data/ -r test/data/ --include-files "*.vtu" --junit-xml dir_mode_junit.xml
  artifacts:
    reports:
      junit: dir_mode_junit.xml

test_coverage_report:
  stage: coverage
  extends: .install_dependencies
  script:
    - tox -e coverage
  coverage: '/TOTAL.*\s([.\d]+)%/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - cov_report
    expire_in: 30 minutes

build_docs:
  stage: documentation
  extends: .install_dependencies
  script:
    - pip install sphinx sphinx-mdinclude pydata-sphinx-theme -r requirements.txt
    - cd docs
    - sphinx-apidoc -f -o build ../
    - make html
  artifacts:
    paths:
      - docs/build
    expire_in: 30 minutes

pages:
  stage: pages
  extends: .regular_job
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  needs:
    - job: test_coverage_report
      artifacts: true
    - job: build_docs
      artifacts: true
  script:
    - mkdir -p public/coverage
    - mv cov_report/* public/coverage/
    - mv docs/build/html/* public/
  artifacts:
    paths:
      - public
    expire_in: 30 minutes

pypi:
  stage: deploy
  extends: .regular_job
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $FIELDCOMPARE_RELEASE_VERSION
      when: never
      changes:
        paths:
          - pyproject.toml
  script:
    - echo "Check if fieldcompare version increased since the last release tag..."
    - python -m pip install -e .
    - python -c "import fieldcompare; print(fieldcompare.__version__)" > current_fieldcompare_version.txt
    - git fetch --tags
    - git checkout $(git describe --tags $(git rev-list --tags --max-count=1))
    - python -c "import fieldcompare; print(fieldcompare.__version__)" > old_fieldcompare_version.txt
    - python -m pip uninstall --yes fieldcompare
    - git checkout $CI_COMMIT_SHA
    - |
      if cmp -s current_fieldcompare_version.txt old_fieldcompare_version.txt; then
          echo "Build fieldcompare package and upload to PyPI..."
          python -m pip install --upgrade build twine
          python -m build
          python -m twine upload dist/*
          FIELDCOMPARE_RELEASE_VERSION=$(cat current_fieldcompare_version.txt | xargs echo)"
          if [[ "$FIELDCOMPARE_RELEASE_VERSION" =~ ^(\d+\.)?(\d+\.)?(\*|\d+)$ ]]; then
              echo "Trigger release tag $FIELDCOMPARE_RELEASE_VERSION"
              curl --request POST --form "token=$CI_JOB_TOKEN" \
                                  --form ref=$CI_COMMIT_BRANCH \
                                  --form "variables[FIELDCOMPARE_RELEASE_VERSION]=$FIELDCOMPARE_RELEASE_VERSION" \
                                  "https://gitlab.com/api/v4/projects/32838547/trigger/pipeline"
          else
              echo "Version string $FIELDCOMPARE_RELEASE_VERSION is not a valid version. Refusing to deploy."
          fi
      else
          echo "Version is still the same. Skipping deployment."
      fi
  when: on_success

release:
  stage: release
  extends: .release_job
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger"
  script:
    - echo $FIELDCOMPARE_RELEASE_VERSION > release_version.txt
    - python -m pip install -e .
    - python -c "import fieldcompare; print(fieldcompare.__version__)" > fieldcompare_version.txt
    - cmp -s fieldcompare_version.txt release_version.txt
    - echo "Releasing fieldcompare version $FIELDCOMPARE_RELEASE_VERSION"
  release:
    tag_name: "$FIELDCOMPARE_RELEASE_VERSION"
    description: "fieldcompare release $FIELDCOMPARE_RELEASE_VERSION"
    ref: "$CI_COMMIT_SHA"
    assets:
      links:
        - name: 'Python package on PyPI'
          url: 'https://pypi.org/project/fieldcompare/$FIELDCOMPARE_RELEASE_VERSION/'
