stages:
  - test
  - coverage
  - pages

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: '$CI_COMMIT_BRANCH =~ /^(main|releases\/)/'

default:
  image: ubuntu:20.04

variables:
  PY_VERSION: "3.9"
  MESHIO_VERSION: "5.2.2"

.install_dependencies:
  before_script:
      - apt-get update && apt-get install --no-install-recommends --yes python$PY_VERSION python3-pip
      - ln -sf /usr/bin/python$PY_VERSION /usr/bin/python
      - python -m pip install pytest colorama meshio[all]==$MESHIO_VERSION

.test_base:
  extends: .install_dependencies
  stage: test
  script: cd test && pytest --verbose --junit-xml test_report.xml
  artifacts:
    reports:
      junit: test/test_report.xml

test:
  extends: .test_base
  parallel:
    matrix:
      - PY_VERSION: ["3.8", "3.9"]
        MESHIO_VERSION: ["4.4", "5.2.2"]

test_coverage_report:
  stage: coverage
  extends: .install_dependencies
  script:
    - python -m pip install pytest-cov
    - |
      cd test && python -m pytest --cov-report xml:coverage.xml \
                                  --cov-report html:cov_report \
                                  --cov-report term \
                                  --cov=fieldcompare
  artifacts:
    reports:
      cobertura: test/coverage.xml
    paths:
      - test/cov_report
    expire_in: 30 minutes

pages:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: pages
  needs:
    - job: test_coverage_report
      artifacts: true
  script:
    - mkdir public
    - mv test/cov_report/* public/
  artifacts:
    paths:
      - public
    expire_in: 30 minutes
