stages:
  - test
  - coverage
  - pages

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: '$CI_COMMIT_BRANCH =~ /^(main|releases\/)/'

default:
  image: python:3.9

cache:
  paths:
    - .cache/pip

.install_dependencies:
  before_script:
      - python --version
      - pip install --upgrade pip
      - pip install tox

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PY_VERSION: "3.9"

test:
  image: python:$PY_VERSION
  extends: .install_dependencies
  stage: test
  artifacts:
    reports:
      junit: test_report.xml
  script:
    - tox -e py${PY_VERSION/./}
  parallel:
    matrix:
      - PY_VERSION: ["3.8", "3.9", "3.10"]

test_coverage_report:
  stage: coverage
  extends: .install_dependencies
  script:
    - tox -e coverage
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - cov_report
    expire_in: 30 minutes

pages:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: pages
  needs:
    - job: test_coverage_report
      artifacts: true
  script:
    - mkdir public
    - mv cov_report/* public/
  artifacts:
    paths:
      - public
    expire_in: 30 minutes
