stages:
  - test
  - coverage
  - pages

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: '$CI_COMMIT_BRANCH =~ /^(main|releases\/)/'

default:
  image: python:3.9

cache:
  paths:
    - .cache/pip

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PY_VERSION: "3.9"
  MESHIO_VERSION: "5.2.2"

.install_dependencies:
  before_script:
      - python --version
      - python -m venv venv
      - source venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install -e .[full]

.test_base:
  extends: .install_dependencies
  stage: test
  script:
    - pytest --verbose --junit-xml test_report.xml
  artifacts:
    reports:
      junit: test_report.xml

test:
  image: python:$PY_VERSION
  extends: .test_base
  parallel:
    matrix:
      - PY_VERSION: ["3.8", "3.9"]
        MESHIO_VERSION: ["4.4", "5.2.2"]

test_coverage_report:
  stage: coverage
  extends: .install_dependencies
  script:
    - python -m pip install pytest-cov
    - |
      pytest --cov-report xml:coverage.xml \
             --cov-report html:cov_report \
             --cov-report term \
             --cov=fieldcompare
  artifacts:
    reports:
      cobertura: coverage.xml
    paths:
      - cov_report
    expire_in: 30 minutes

pages:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: pages
  needs:
    - job: test_coverage_report
      artifacts: true
  script:
    - mkdir public
    - mv cov_report/* public/
  artifacts:
    paths:
      - public
    expire_in: 30 minutes
